# Blink API http://bl.7yue.pro/dev/index.html
@API_BASE_URL = http://bl.7yue.pro/v1/
@APP_KEY = *

## 一、期刊(http://bl.7yue.pro/dev/classic.html)

### 1️⃣ 获取最新一期
GET {{API_BASE_URL}}classic/latest
appkey: {{APP_KEY}}

### 2️⃣ 获取当前一期的下一期
GET {{API_BASE_URL}}classic/1/next
appkey: {{APP_KEY}}

### 3️⃣ 获取某一期详细信息
GET {{API_BASE_URL}}classic/300/2
appkey: {{APP_KEY}}

### 4️⃣ 获取当前一期的上一期
GET {{API_BASE_URL}}classic/2/previous
appkey: {{APP_KEY}}

### 5️⃣ 获取点赞信息
GET {{API_BASE_URL}}classic/200/2/favor
appkey: {{APP_KEY}}

### 6️⃣ 获取我喜欢的期刊
GET {{API_BASE_URL}}classic/favor
appkey: {{APP_KEY}}

## 二、书籍(http://bl.7yue.pro/dev/book.html)
### 1️⃣ 获取热门书籍(概要)
GET {{API_BASE_URL}}book/hot_list
appkey: {{APP_KEY}}

### 2️⃣ 获取书籍短评
GET {{API_BASE_URL}}book/1/short_comment
appkey: {{APP_KEY}}
content-type: application/json;charset=utf-8;

### 3️⃣ 获取喜欢书籍数量
GET {{API_BASE_URL}}book/favor/count
appkey: {{APP_KEY}}

### 4️⃣ 获取书籍点赞情况
GET {{API_BASE_URL}}book/1/favor
appkey: {{APP_KEY}}

### 5️⃣ 新增短评
POST {{API_BASE_URL}}book/add/short_comment
appkey: {{APP_KEY}}
content-type: application/json

{
  "book_id": 1,
  "content": "good book"
}

### 6️⃣ 获取热搜关键字
GET {{API_BASE_URL}}book/hot_keyword
appkey: {{APP_KEY}}

### 7️⃣ 书籍搜索
GET {{API_BASE_URL}}book/search
appkey: {{APP_KEY}}
content-type: application/json

{
  "start": 0,
  "count": 20,
  "summary": 0,
  "q": "python"
}

### 8️⃣ 获取书籍详细信息
GET {{API_BASE_URL}}book/1/detail
appkey: {{APP_KEY}}

## 三、点赞(http://bl.7yue.pro/dev/like.html)
### 1️⃣ 点赞
POST {{API_BASE_URL}}like
appkey: {{APP_KEY}}
content-type: application/json

{
  "art_id": 1,
  "type": 100
}

### 2️⃣ 取消点赞
POST {{API_BASE_URL}}like/cancel
appkey: {{APP_KEY}}
content-type: application/json

{
  "art_id": 1,
  "type": 100
}
